# Generated by Django 2.2.5 on 2020-02-23 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.TextField(max_length=255, primary_key=True, serialize=False)),
                ('spaceStatus', models.IntegerField()),
                ('booked_status', models.BooleanField()),
                ('openCloseStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Economy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField(unique=True)),
                ('value', models.IntegerField()),
                ('validity', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('total_agent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(max_length=255)),
                ('endTime', models.CharField(max_length=255)),
                ('state', models.BooleanField(default=True)),
                ('paidStatus', models.BooleanField(default=False)),
                ('total_amount', models.FloatField()),
                ('received', models.FloatField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Agents')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bookedAgents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Agents')),
                ('booked_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Booking')),
            ],
        ),
        migrations.AddField(
            model_name='agents',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Venue'),
        ),
    ]
